spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
#        git:
#          uri: https://github.com/linanlong123/sp-config
#          searchPaths: config
 #         username: linanlong123
 #         password: Xiaoli130058

  rabbitmq:
    host: 192.168.72.140
    port: 5672
    username: admin
    password: admin
        
server:
  port: 6001
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh